openapi: 3.0.3
info:
  title: f8 Engine API (NATS binding)
  version: "v1"
  description: >
    Engine runtime control: apply graph diffs, fetch snapshots. Transport is NATS request/reply.
servers:
  - url: nats://local
    description: NATS request/reply
paths:
  /engine/status:
    get:
      summary: Engine status/health
      description: Current engine lifecycle state, uptime, and graph revision.
      operationId: getEngineStatus
      x-nats-subject: f8.engine.status
      x-nats-timeout-ms: 1000
      responses:
        "200":
          description: Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineStatusReply'
  /engine/catalog:
    get:
      summary: Operator catalog
      description: Returns operators supported by this engine instance (for editor to enable placement).
      operationId: getEngineCatalog
      x-nats-subject: f8.engine.catalog
      x-nats-timeout-ms: 1000
      responses:
        "200":
          description: Catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineCatalogReply'
  /engine/pause:
    post:
      summary: Pause execution
      description: Pause the engine at the next safe point.
      operationId: pauseEngine
      x-nats-subject: f8.engine.pause
      x-nats-timeout-ms: 1000
      responses:
        "200":
          description: Ack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckReply'
  /engine/resume:
    post:
      summary: Resume execution
      description: Resume a paused engine.
      operationId: resumeEngine
      x-nats-subject: f8.engine.resume
      x-nats-timeout-ms: 1000
      responses:
        "200":
          description: Ack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckReply'
  /engine/stop:
    post:
      summary: Stop execution
      description: Gracefully stop the engine.
      operationId: stopEngine
      x-nats-subject: f8.engine.stop
      x-nats-timeout-ms: 1000
      responses:
        "200":
          description: Ack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckReply'
  /engine/graph/apply:
    post:
      summary: Apply graph diff/replace
      description: Engine applies a graph update at a safe point and returns the new revision (KV rev).
      operationId: applyEngineGraph
      x-nats-subject: f8.engine.graph.apply
      x-nats-timeout-ms: 2000
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GraphApplyRequest'
      responses:
        "200":
          description: Apply result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphApplyReply'
  /engine/graph/snapshot:
    get:
      summary: Fetch current graph snapshot
      description: Returns the active graph and KV revision/etag.
      operationId: getEngineGraphSnapshot
      x-nats-subject: f8.engine.graph.snapshot
      x-nats-timeout-ms: 2000
      responses:
        "200":
          description: Snapshot result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphSnapshotReply'
components:
  schemas:
    Envelope:
      $ref: '../master.yaml#/components/schemas/Envelope'
    AckReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status]
    GraphApplyRequest:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                mode:
                  type: string
                  enum: [patch, replace]
                  default: patch
                expectedRevision:
                  type: integer
                  description: Optional expected KV revision/etag for concurrency control.
                graph:
                  type: object
                  description: Graph document to apply (full or patch per mode).
              required: [graph]
    GraphApplyReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                revision:
                  type: integer
                  description: KV revision after apply.
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status]
    GraphSnapshotReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                revision:
                  type: integer
                  description: Current KV revision/etag.
                graph:
                  type: object
                  description: Active graph snapshot.
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status]
    EngineStatusReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                state:
                  type: string
                  enum: [starting, running, paused, stopped, error]
                uptimeMs:
                  type: integer
                graphRevision:
                  type: integer
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status, state]
    EngineCatalogReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                operators:
                  type: array
                  items:
                    type: object
                    properties:
                      operatorClass:
                        type: string
                      label:
                        type: string
                      rendererId:
                        type: string
                    required: [operatorClass]
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status]
