[pytest]
testpaths =
    tests
    packages/f8pysdk/tests
    packages/f8studio_core/tests
    packages/f8studio_server/tests
    packages/f8media_gateway/tests
norecursedirs =
    tmp
    .tmp
    build
filterwarnings =
    ignore:distutils Version classes are deprecated\. Use packaging\.version instead\.:DeprecationWarning
