schemaVersion: f8serviceEntry/1
serviceClass: f8.dl.detsorter
label: DL Detection Sorter
version: 0.0.1
launch:
  command: pixi
  args:
  - run
  - -e
  - onnx
  - f8pydl_detsorter
  env: {}
  workdir: ../../..
