from __future__ import annotations

from .constants import (
    CLASSIFIER_SERVICE_CLASS,
    DETECTOR_SERVICE_CLASS,
    HUMAN_DETECTOR_SERVICE_CLASS,
    OPTFLOW_SERVICE_CLASS,
)

__all__ = [
    "CLASSIFIER_SERVICE_CLASS",
    "DETECTOR_SERVICE_CLASS",
    "HUMAN_DETECTOR_SERVICE_CLASS",
    "OPTFLOW_SERVICE_CLASS",
]
