schemaVersion: f8serviceEntry/1
serviceClass: f8.proclauncher
label: Proc Launcher
version: 0.0.1
launch:
  command: pixi
  args:
  - run
  - -e
  - proclauncher
  - f8proclauncher
  env: {}
  workdir: ${F8_PACKAGE_ROOT}/extensions/f8proclauncher
