// Generated by scripts/web_studio/generate_contracts.py; do not edit.
export type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };

export type AcceptedResponse = {
  readonly "accepted": boolean;
};

export type AccessMode = "object_and_mapping";

export type AgentApproval = {
  readonly "approvalId": string;
  readonly "toolCallId": string;
  readonly "toolName": string;
  readonly "argumentsHash": string;
  readonly "targetGraphRevision": number;
  readonly "expiresAt": string;
  readonly "status": ApprovalStatus;
  readonly "resolvedAt"?: string | null;
};

export type AgentArtifact = {
  readonly "artifactId": string;
  readonly "kind": "deployment" | "diagnostics" | "graph_patch" | "monitor" | "text";
  readonly "title": string;
  readonly "payload": JsonValue;
  readonly "createdAt": string;
};

export type AgentImage = {
  readonly "name": string;
  readonly "dataUrl": string;
};

export type AgentMessage = {
  readonly "messageId": string;
  readonly "role": "assistant" | "system" | "user";
  readonly "content": string;
  readonly "createdAt": string;
  readonly "images"?: ReadonlyArray<AgentImage>;
  readonly "providerId"?: string;
  readonly "modelId"?: string;
};

export type AgentProviderSummary = {
  readonly "providerId": string;
  readonly "displayName": string;
  readonly "models": ReadonlyArray<string>;
  readonly "configured": boolean;
  readonly "deterministic"?: boolean;
  readonly "supportsImages"?: boolean;
  readonly "modelCapabilities"?: ReadonlyArray<ModelCapabilities>;
};

export type AgentRunStatus = "cancelled" | "failed" | "idle" | "running" | "succeeded" | "waiting_for_approval";

export type AgentSessionRecord = {
  readonly "sessionId": string;
  readonly "projectId": string;
  readonly "title": string;
  readonly "providerId": string;
  readonly "modelId": string;
  readonly "status": AgentRunStatus;
  readonly "createdAt": string;
  readonly "updatedAt": string;
  readonly "messages"?: ReadonlyArray<AgentMessage>;
  readonly "toolCalls"?: ReadonlyArray<AgentToolCall>;
  readonly "artifacts"?: ReadonlyArray<AgentArtifact>;
  readonly "approval"?: null | AgentApproval;
  readonly "errorMessage"?: string;
  readonly "tracebackId"?: string;
  readonly "autoTitlePending"?: boolean;
};

export type AgentSessionSummary = {
  readonly "sessionId": string;
  readonly "projectId": string;
  readonly "title": string;
  readonly "providerId": string;
  readonly "modelId": string;
  readonly "status": AgentRunStatus;
  readonly "updatedAt": string;
  readonly "messageCount": number;
};

export type AgentToolCall = {
  readonly "toolCallId": string;
  readonly "toolName": string;
  readonly "arguments": Readonly<Record<string, JsonValue>>;
  readonly "argumentsHash": string;
  readonly "targetGraphRevision": number | null;
  readonly "status": ToolCallStatus;
  readonly "createdAt": string;
  readonly "updatedAt": string;
  readonly "result"?: JsonValue;
  readonly "errorMessage"?: string;
  readonly "tracebackId"?: string;
};

export type ApplyUnityInstallRequest = {
  readonly "planId": string;
  readonly "confirm": boolean;
};

export type ApprovalStatus = "approved" | "cancelled" | "denied" | "expired" | "invalidated" | "pending";

export type AssetExport = {
  readonly "schemaVersion": string;
  readonly "asset": AssetRecord;
  readonly "versions": ReadonlyArray<AssetVersion>;
};

export type AssetKind = "component" | "modding_recipe" | "variant";

export type AssetRecord = {
  readonly "assetId": string;
  readonly "kind": AssetKind;
  readonly "name": string;
  readonly "description": string;
  readonly "tags": ReadonlyArray<string>;
  readonly "currentVersion": number;
  readonly "createdAt": string;
  readonly "updatedAt": string;
  readonly "content": JsonValue;
};

export type AssetSummary = {
  readonly "assetId": string;
  readonly "kind": AssetKind;
  readonly "name": string;
  readonly "description": string;
  readonly "tags": ReadonlyArray<string>;
  readonly "currentVersion": number;
  readonly "createdAt": string;
  readonly "updatedAt": string;
};

export type AssetVersion = {
  readonly "assetId": string;
  readonly "version": number;
  readonly "createdAt": string;
  readonly "content": JsonValue;
};

export type AudioSessionAnswer = {
  readonly "sessionId": string;
  readonly "source": string;
  readonly "sdp": string;
  readonly "type": "answer";
  readonly "sampleRate": number;
  readonly "channels": number;
  readonly "transportPolicy": string;
};

export type AudioSessionOffer = {
  readonly "source": string;
  readonly "sdp": string;
  readonly "type"?: string;
};

export type BindOperatorServiceOp = {
  readonly "op": "bindOperatorService";
  readonly "nodeId": string;
  readonly "serviceId": string;
};

export type BrowserIceServer = {
  readonly "urls": ReadonlyArray<string>;
  readonly "username"?: string | null;
  readonly "credential"?: string | null;
};

export type BrowserRtcConfiguration = {
  readonly "iceServers"?: ReadonlyArray<BrowserIceServer>;
  readonly "iceTransportPolicy"?: "all" | "relay";
};

export type CapabilitiesResponse = {
  readonly "protocol_version": "f8studio-api/1";
  readonly "capabilities": ServerCapabilities;
};

export type CatalogSnapshot = {
  readonly "services": ReadonlyArray<F8ServiceSpec>;
  readonly "operators": ReadonlyArray<F8OperatorSpec>;
};

export type ChoiceAnswer = {
  readonly "type": "choice";
  readonly "choice": string;
  readonly "probabilities": Readonly<Record<string, number>>;
  readonly "confidence": number;
};

export type ChoiceQuestion = {
  readonly "type": "choice";
  readonly "instructions": string | Readonly<Record<string, JsonValue>> | ReadonlyArray<JsonValue>;
  readonly "criteria": Readonly<Record<string, string | Readonly<Record<string, JsonValue>> | ReadonlyArray<JsonValue> | null>>;
};

export type ConnectEdgeOp = {
  readonly "op": "connectEdge";
  readonly "edge": GraphEdge;
};

export type CreateAgentSessionRequest = {
  readonly "projectId": string;
  readonly "title"?: string;
  readonly "providerId"?: string;
  readonly "modelId"?: string;
};

export type CreateAssetRequest = {
  readonly "kind": AssetKind;
  readonly "name": string;
  readonly "content": JsonValue;
  readonly "description"?: string;
  readonly "tags"?: ReadonlyArray<string>;
  readonly "assetId"?: string | null;
};

export type CreateCatalogNodeRequest = {
  readonly "kind": "operator" | "service";
  readonly "nodeId": string;
  readonly "serviceClass": string;
  readonly "serviceId"?: string | null;
  readonly "operatorClass"?: string | null;
  readonly "name"?: string | null;
};

export type CreateEditorSessionRequest = {
  readonly "language": "json" | "python";
  readonly "text": string;
  readonly "filename"?: string;
  readonly "supportFiles"?: ReadonlyArray<EditorSupportFile>;
  readonly "projectId"?: string;
  readonly "nodeId"?: string;
  readonly "fieldName"?: string;
};

export type CreateNodeOp = {
  readonly "op": "createNode";
  readonly "node": ServiceNode | OperatorNode;
  readonly "layout"?: null | NodeLayout;
};

export type CreateProjectRequest = {
  readonly "name"?: string;
  readonly "description"?: string;
  readonly "projectId"?: string | null;
};

export type CreateProjectVersionRequest = {
  readonly "name"?: string;
};

export type CreateProviderConnection = {
  readonly "displayName": string;
  readonly "protocol": "anthropic" | "openai_chat" | "openai_responses" | "systemone";
  readonly "endpoint": string;
  readonly "model"?: string;
  readonly "models"?: ReadonlyArray<string>;
  readonly "apiKey"?: string;
  readonly "supportsImage"?: boolean;
  readonly "modelCapabilities"?: ReadonlyArray<ModelCapabilities>;
};

export type CurrentSeverity = "" | "critical" | "error" | "info" | "warning";

export type DecisionRequest = {
  readonly "state": string | Readonly<Record<string, JsonValue>> | ReadonlyArray<JsonValue>;
  readonly "questions": Readonly<Record<string, ChoiceQuestion | ScoreQuestion | NoulQuestion>>;
  readonly "providerId"?: string;
  readonly "imageDataUrl"?: string | null;
};

export type DecisionResult = {
  readonly "model": string;
  readonly "answers": Readonly<Record<string, ChoiceAnswer | ScoreAnswer | NoulAnswer>>;
  readonly "usage": DecisionUsage;
};

export type DecisionUsage = {
  readonly "input_tokens": number;
  readonly "output_tokens": number;
};

export type DeleteNodeOp = {
  readonly "op": "deleteNode";
  readonly "nodeId": string;
};

export type DeployJob = {
  readonly "jobId": string;
  readonly "requestId": string;
  readonly "projectId": string;
  readonly "sourceGraphRevision": number;
  readonly "sourceSemanticRevision": string;
  readonly "status": JobStatus;
  readonly "createdAt": string;
  readonly "updatedAt": string;
  readonly "serviceResults": ReadonlyArray<ServiceDeployResult>;
  readonly "errorMessage": string;
};

export type DeployProjectRequest = {
  readonly "requestId": string;
  readonly "expectedGraphRevision": number;
  readonly "forceApply"?: boolean;
};

export type DetectModdingTargetRequest = {
  readonly "targetPath": string;
};

export type DisconnectEdgeOp = {
  readonly "op": "disconnectEdge";
  readonly "edgeId": string;
};

export type EdgeStrategy = "latest" | "queue";

export type EditorAnalysis = {
  readonly "sessionId": string;
  readonly "version": number;
  readonly "diagnostics": ReadonlyArray<EditorDiagnostic>;
  readonly "engine": string;
};

export type EditorDiagnostic = {
  readonly "severity": "error" | "information" | "warning";
  readonly "message": string;
  readonly "source": string;
  readonly "path": string;
  readonly "range": EditorRange;
  readonly "rule": string | null;
};

export type EditorLanguageResult = {
  readonly "sessionId": string;
  readonly "version": number;
  readonly "result": JsonValue;
};

export type EditorPosition = {
  readonly "line": number;
  readonly "column": number;
};

export type EditorPositionRequest = {
  readonly "line": number;
  readonly "column": number;
};

export type EditorRange = {
  readonly "start": EditorPosition;
  readonly "end": EditorPosition;
};

export type EditorSessionRecord = {
  readonly "sessionId": string;
  readonly "language": "json" | "python";
  readonly "filename": string;
  readonly "version": number;
  readonly "text": string;
};

export type EditorSupportFile = {
  readonly "path": string;
  readonly "content": string;
};

export type EventEnvelope = {
  readonly "eventId": string;
  readonly "serverEpoch": string;
  readonly "sequence": number;
  readonly "type": "agent.session.deleted" | "agent.session.updated" | "asset.created" | "asset.deleted" | "asset.updated" | "deploy.cancelled" | "deploy.finished" | "deploy.queued" | "deploy.running" | "graph.committed" | "media.error" | "presentation.command" | "project.created" | "project.deleted" | "project.updated" | "runtime.error" | "server.error" | "service.log" | "service.process_started" | "service.process_stopped";
  readonly "scope": string;
  readonly "timestamp": string;
  readonly "payload": JsonValue;
};

export type ExchangeDefinitions = {
  readonly "services"?: Readonly<Record<string, F8ServiceSpec>>;
  readonly "operators"?: Readonly<Record<string, F8OperatorSpec>>;
};

export type ExchangeMetadata = {
  readonly "graphId": string;
  readonly "projectId": string;
};

export type ExchangeOperator = {
  readonly "nodeId": string;
  readonly "name": string;
  readonly "serviceId": string;
  readonly "definitionRef": string;
  readonly "portIds"?: Readonly<Record<string, string>>;
  readonly "stateValues"?: Readonly<Record<string, JsonValue>>;
  readonly "enabled"?: boolean;
};

export type ExchangePresentation = {
  readonly "layout"?: ReadonlyArray<NodeLayout>;
  readonly "nodeOrder"?: ReadonlyArray<string>;
};

export type ExchangeService = {
  readonly "nodeId": string;
  readonly "name": string;
  readonly "definitionRef": string;
  readonly "portIds"?: Readonly<Record<string, string>>;
  readonly "stateValues"?: Readonly<Record<string, JsonValue>>;
  readonly "enabled"?: boolean;
};

export type F8AnyTypeSchema = {
  readonly "type": "any";
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "default"?: JsonValue;
  readonly "examples"?: ReadonlyArray<JsonValue>;
  readonly "$comment"?: string;
};

export type F8ArrayTypeSchema = {
  readonly "type": "array";
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "default"?: JsonValue;
  readonly "examples"?: ReadonlyArray<JsonValue>;
  readonly "$comment"?: string;
  readonly "items": F8StringTypeSchema | F8NumberTypeSchema | F8IntegerTypeSchema | F8BooleanTypeSchema | F8NullTypeSchema | F8ComplexObjectTypeSchema | F8ArrayTypeSchema | F8AnyTypeSchema;
};

export type F8BooleanTypeSchema = {
  readonly "type": "boolean";
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "default"?: JsonValue;
  readonly "examples"?: ReadonlyArray<JsonValue>;
  readonly "$comment"?: string;
  readonly "enum"?: ReadonlyArray<JsonValue>;
};

export type F8CollectionEditPolicy = {
  readonly "canAdd"?: boolean;
  readonly "canDelete"?: boolean;
  readonly "canEditExisting"?: boolean;
};

export type F8Command = {
  readonly "name": string;
  readonly "description"?: string;
  readonly "definitionProtected"?: boolean;
  readonly "showOnNode"?: boolean;
  readonly "params"?: ReadonlyArray<F8CommandParam>;
};

export type F8CommandParam = {
  readonly "name": string;
  readonly "valueSchema": F8StringTypeSchema | F8NumberTypeSchema | F8IntegerTypeSchema | F8BooleanTypeSchema | F8NullTypeSchema | F8ComplexObjectTypeSchema | F8ArrayTypeSchema | F8AnyTypeSchema;
  readonly "description"?: string;
  readonly "valueRequired"?: boolean;
  readonly "control"?: F8UiControlSpec;
};

export type F8ComplexObjectTypeSchema = {
  readonly "type": "object";
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "default"?: JsonValue;
  readonly "examples"?: ReadonlyArray<JsonValue>;
  readonly "$comment"?: string;
  readonly "properties": Readonly<Record<string, F8StringTypeSchema | F8NumberTypeSchema | F8IntegerTypeSchema | F8BooleanTypeSchema | F8NullTypeSchema | F8ComplexObjectTypeSchema | F8ArrayTypeSchema | F8AnyTypeSchema>>;
  readonly "required"?: ReadonlyArray<string>;
  readonly "additionalProperties"?: boolean;
};

export type F8DataPayloadSpec = {
  readonly "kind": F8DataPortPayloadKind;
  readonly "valueSchema"?: F8StringTypeSchema | F8NumberTypeSchema | F8IntegerTypeSchema | F8BooleanTypeSchema | F8NullTypeSchema | F8ComplexObjectTypeSchema | F8ArrayTypeSchema | F8AnyTypeSchema;
  readonly "metadataSchema"?: F8StringTypeSchema | F8NumberTypeSchema | F8IntegerTypeSchema | F8BooleanTypeSchema | F8NullTypeSchema | F8ComplexObjectTypeSchema | F8ArrayTypeSchema | F8AnyTypeSchema;
  readonly "schemaVersion"?: number;
  readonly "formats"?: ReadonlyArray<string>;
};

export type F8DataPortDelivery = "fifo" | "latest" | "reliable";

export type F8DataPortPayloadKind = "audio_chunk" | "bytes" | "json" | "video_frame";

export type F8DataPortSpec = {
  readonly "name": string;
  readonly "valueSchema": F8StringTypeSchema | F8NumberTypeSchema | F8IntegerTypeSchema | F8BooleanTypeSchema | F8NullTypeSchema | F8ComplexObjectTypeSchema | F8ArrayTypeSchema | F8AnyTypeSchema;
  readonly "payload"?: F8DataPayloadSpec;
  readonly "stream"?: F8DataStreamSpec;
  readonly "description"?: string;
  readonly "definitionProtected"?: boolean;
  readonly "showOnNode"?: boolean;
  readonly "payloadKind"?: F8DataPortPayloadKind;
  readonly "delivery"?: F8DataPortDelivery;
};

export type F8DataStreamCongestion = "block" | "drop";

export type F8DataStreamPriority = "data" | "interactive" | "real_time";

export type F8DataStreamReliability = "best_effort" | "reliable";

export type F8DataStreamSpec = {
  readonly "delivery"?: F8DataPortDelivery;
  readonly "reliability"?: F8DataStreamReliability;
  readonly "congestion"?: F8DataStreamCongestion;
  readonly "priority"?: F8DataStreamPriority;
};

export type F8DynamicBindingsInputsSpec = {
  readonly "enabled": boolean;
  readonly "source": Source;
  readonly "type_name"?: string;
  readonly "module_name"?: string;
  readonly "schema_mode"?: SchemaMode;
  readonly "access_mode"?: AccessMode;
};

export type F8DynamicBindingsOutputsSpec = {
  readonly "enabled": boolean;
  readonly "source": Source2;
  readonly "type_name"?: string;
  readonly "module_name"?: string;
  readonly "schema_mode"?: SchemaMode;
  readonly "access_mode"?: AccessMode;
};

export type F8DynamicBindingsSpec = {
  readonly "inputs"?: F8DynamicBindingsInputsSpec;
  readonly "states"?: F8DynamicBindingsStatesSpec;
  readonly "outputs"?: F8DynamicBindingsOutputsSpec;
};

export type F8DynamicBindingsStatesSpec = {
  readonly "enabled": boolean;
  readonly "source": Source1;
  readonly "type_name"?: string;
  readonly "module_name"?: string;
  readonly "schema_mode"?: SchemaMode;
  readonly "access_mode"?: AccessMode;
};

export type F8EditorAssistSpec = {
  readonly "version": number;
  readonly "language": string;
  readonly "python"?: F8PythonEditorAssistSpec;
};

export type F8ExecPortSpec = {
  readonly "name": string;
  readonly "label"?: string;
  readonly "description"?: string;
  readonly "definitionProtected"?: boolean;
};

export type F8IntegerTypeSchema = {
  readonly "type": "integer";
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "default"?: JsonValue;
  readonly "examples"?: ReadonlyArray<JsonValue>;
  readonly "$comment"?: string;
  readonly "enum"?: ReadonlyArray<JsonValue>;
  readonly "minimum"?: number;
  readonly "maximum"?: number;
  readonly "exclusiveMinimum"?: number;
  readonly "exclusiveMaximum"?: number;
  readonly "multipleOf"?: number;
};

export type F8MonitorCpu = {
  readonly "processPercent"?: number | null;
  readonly "systemPercent"?: number | null;
};

export type F8MonitorError = {
  readonly "countWindow"?: number;
  readonly "lastNodeId"?: string;
  readonly "lastCode"?: string;
  readonly "lastMessage"?: string;
  readonly "lastSeverity"?: LastSeverity;
  readonly "lastFingerprint"?: string;
  readonly "lastRepeatCount"?: number;
  readonly "lastTsMs"?: number | null;
  readonly "currentNodeId"?: string;
  readonly "currentCode"?: string;
  readonly "currentMessage"?: string;
  readonly "currentSeverity"?: CurrentSeverity;
  readonly "currentTsMs"?: number | null;
};

export type F8MonitorFrame = {
  readonly "observed"?: number;
  readonly "processed"?: number;
  readonly "dropped"?: number;
  readonly "localOnlyEmits"?: number;
  readonly "routedCrossEmits"?: number;
  readonly "suppressedCrossPublishes"?: number;
  readonly "callbackDeliveries"?: number;
  readonly "bufferPullDeliveries"?: number;
};

export type F8MonitorGpu = {
  readonly "vendor"?: string;
  readonly "deviceIndex"?: number | null;
  readonly "utilPercent"?: number | null;
  readonly "memoryUsedBytes"?: number | null;
  readonly "memoryTotalBytes"?: number | null;
  readonly "available"?: boolean;
};

export type F8MonitorMemory = {
  readonly "rssBytes"?: number;
  readonly "vmsBytes"?: number;
};

export type F8MonitorQueue = {
  readonly "depth"?: number;
};

export type F8MonitorSnapshot = {
  readonly "schemaVersion": SchemaVersion1;
  readonly "serviceId": string;
  readonly "serviceClass": string;
  readonly "nodeId": string;
  readonly "tsMs": number;
  readonly "alive": boolean;
  readonly "ready": boolean;
  readonly "active": boolean;
  readonly "uptimeMs": number;
  readonly "cpu": F8MonitorCpu;
  readonly "memory": F8MonitorMemory;
  readonly "gpu": F8MonitorGpu;
  readonly "frame": F8MonitorFrame;
  readonly "timing": F8MonitorTiming;
  readonly "queue": F8MonitorQueue;
  readonly "error": F8MonitorError;
};

export type F8MonitorTiming = {
  readonly "processMsAvg"?: number | null;
  readonly "processMsP95"?: number | null;
  readonly "waitMsAvg"?: number | null;
  readonly "waitMsP95"?: number | null;
  readonly "latencyMsAvg"?: number | null;
  readonly "latencyMsP95"?: number | null;
};

export type F8NullTypeSchema = {
  readonly "type": "null";
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "default"?: JsonValue;
  readonly "examples"?: ReadonlyArray<JsonValue>;
  readonly "$comment"?: string;
  readonly "enum"?: ReadonlyArray<JsonValue>;
};

export type F8NumberTypeSchema = {
  readonly "type": "number";
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "default"?: JsonValue;
  readonly "examples"?: ReadonlyArray<JsonValue>;
  readonly "$comment"?: string;
  readonly "enum"?: ReadonlyArray<JsonValue>;
  readonly "minimum"?: number;
  readonly "maximum"?: number;
  readonly "exclusiveMinimum"?: number;
  readonly "exclusiveMaximum"?: number;
  readonly "multipleOf"?: number;
};

export type F8OperatorSchemaVersion = "f8operator/1";

export type F8OperatorSpec = {
  readonly "operatorClass": string;
  readonly "serviceClass": string;
  readonly "label": string;
  readonly "specKind"?: "operator";
  readonly "schemaVersion"?: F8OperatorSchemaVersion;
  readonly "rendererClass"?: string;
  readonly "version"?: string;
  readonly "description"?: string;
  readonly "tags"?: ReadonlyArray<string>;
  readonly "paletteCategory"?: string;
  readonly "hiddenInPalette"?: boolean;
  readonly "stateFields"?: ReadonlyArray<F8StateSpec>;
  readonly "editPolicy"?: F8SpecEditPolicy;
  readonly "commands"?: ReadonlyArray<F8Command>;
  readonly "execInPorts"?: ReadonlyArray<F8ExecPortSpec>;
  readonly "execOutPorts"?: ReadonlyArray<F8ExecPortSpec>;
  readonly "dataInPorts"?: ReadonlyArray<F8DataPortSpec>;
  readonly "dataOutPorts"?: ReadonlyArray<F8DataPortSpec>;
};

export type F8PythonEditorAssistSpec = {
  readonly "support_files": Readonly<Record<string, string>>;
  readonly "overlay_prefix": string;
  readonly "dynamic_bindings"?: F8DynamicBindingsSpec;
};

export type F8ServiceSchemaVersion = "f8service/1";

export type F8ServiceSpec = {
  readonly "serviceClass": string;
  readonly "label": string;
  readonly "specKind"?: "service";
  readonly "schemaVersion"?: F8ServiceSchemaVersion;
  readonly "rendererClass"?: string;
  readonly "version"?: string;
  readonly "description"?: string;
  readonly "tags"?: ReadonlyArray<string>;
  readonly "paletteCategory"?: string;
  readonly "hiddenInPalette"?: boolean;
  readonly "stateFields"?: ReadonlyArray<F8StateSpec>;
  readonly "editPolicy"?: F8SpecEditPolicy;
  readonly "commands"?: ReadonlyArray<F8Command>;
  readonly "dataInPorts"?: ReadonlyArray<F8DataPortSpec>;
  readonly "dataOutPorts"?: ReadonlyArray<F8DataPortSpec>;
};

export type F8SpecEditPolicy = {
  readonly "stateFields"?: F8CollectionEditPolicy;
  readonly "commands"?: F8CollectionEditPolicy;
  readonly "dataInPorts"?: F8CollectionEditPolicy;
  readonly "dataOutPorts"?: F8CollectionEditPolicy;
  readonly "execInPorts"?: F8CollectionEditPolicy;
  readonly "execOutPorts"?: F8CollectionEditPolicy;
};

export type F8StateAccess = "ro" | "rw" | "wo";

export type F8StateFieldEditPolicy = {
  readonly "canRename"?: boolean;
  readonly "canEditAccess"?: boolean;
  readonly "canEditValueRequired"?: boolean;
  readonly "canEditValueSchema"?: boolean;
};

export type F8StateSpec = {
  readonly "name": string;
  readonly "valueSchema": F8StringTypeSchema | F8NumberTypeSchema | F8IntegerTypeSchema | F8BooleanTypeSchema | F8NullTypeSchema | F8ComplexObjectTypeSchema | F8ArrayTypeSchema | F8AnyTypeSchema;
  readonly "access": F8StateAccess;
  readonly "label"?: string;
  readonly "description"?: string;
  readonly "valueRequired"?: boolean;
  readonly "editPolicy"?: F8StateFieldEditPolicy;
  readonly "control"?: F8UiControlSpec;
  readonly "showOnNode"?: boolean;
  readonly "redactOnPublish"?: boolean;
  readonly "editorAssist"?: F8EditorAssistSpec;
};

export type F8StringTypeSchema = {
  readonly "type": "string";
  readonly "title"?: string;
  readonly "description"?: string;
  readonly "default"?: JsonValue;
  readonly "examples"?: ReadonlyArray<JsonValue>;
  readonly "$comment"?: string;
  readonly "enum"?: ReadonlyArray<JsonValue>;
};

export type F8UiControlKind = "auto" | "button" | "code" | "custom" | "dial" | "multiselect" | "select" | "slider" | "text" | "textarea" | "toggle";

export type F8UiControlSpec = {
  readonly "kind": F8UiControlKind;
  readonly "optionsFromState"?: string;
  readonly "language"?: string;
  readonly "rendererKey"?: string;
};

export type GraphEdge = {
  readonly "edgeId": string;
  readonly "fromNodeId": string;
  readonly "fromPortId": string;
  readonly "toNodeId": string;
  readonly "toPortId": string;
  readonly "kind": GraphEdgeKind;
  readonly "strategy"?: EdgeStrategy;
  readonly "queueSize"?: number;
  readonly "timeoutMs"?: number | null;
};

export type GraphEdgeKind = "data" | "exec" | "state";

export type GraphExchange = {
  readonly "format": string;
  readonly "formatVersion": number;
  readonly "metadata": ExchangeMetadata;
  readonly "definitions": ExchangeDefinitions;
  readonly "services": Readonly<Record<string, ExchangeService>>;
  readonly "operators": Readonly<Record<string, ExchangeOperator>>;
  readonly "connections": ReadonlyArray<GraphEdge>;
  readonly "resources"?: Readonly<Record<string, JsonValue>>;
  readonly "presentation"?: ExchangePresentation;
};

export type GraphPort = {
  readonly "portId": string;
  readonly "name": string;
  readonly "runtimeName": string;
  readonly "kind": PortKind;
  readonly "direction": PortDirection;
  readonly "dataSpec"?: null | F8DataPortSpec;
  readonly "stateSpec"?: null | F8StateSpec;
};

export type HealthStatus = {
  readonly "status": "ok";
  readonly "service": string;
  readonly "version": string;
  readonly "protocol_version": string;
  readonly "server_epoch": string;
};

export type HistoryRequest = {
  readonly "requestId": string;
  readonly "expectedGraphRevision": number;
  readonly "expectedLayoutRevision": number;
};

export type HotkeyBinding = {
  readonly "bindingId": string;
  readonly "accelerator": string;
  readonly "projectId": string;
  readonly "nodeId": string;
  readonly "field": string;
  readonly "status": "configured" | "disabled" | "error" | "registered";
  readonly "message": string;
};

export type InsertFragmentOp = {
  readonly "op": "insertFragment";
  readonly "nodes": ReadonlyArray<ServiceNode | OperatorNode>;
  readonly "edges"?: ReadonlyArray<GraphEdge>;
  readonly "layout"?: ReadonlyArray<NodeLayout>;
};

export type JobStatus = "cancelled" | "failed" | "partially_failed" | "queued" | "running" | "succeeded";

export type LastSeverity = "critical" | "error" | "info" | "warning";

export type LocalCapability = {
  readonly "capability": string;
  readonly "status": "available" | "unavailable" | "unverified";
  readonly "backend": string;
  readonly "reason": string;
};

export type ManagedProcessResult = {
  readonly "serviceId": string;
  readonly "running": boolean;
};

export type MediaFrameMapping = {
  readonly "sessionId": string;
  readonly "mediaTimestamp": number;
  readonly "source": string;
  readonly "streamId": string;
  readonly "streamEpoch": string;
  readonly "frameId": number;
  readonly "captureTimestampMs": number;
  readonly "sentTimestampMs": number;
};

export type MediaGatewayHealth = {
  readonly "status": string;
  readonly "service": string;
  readonly "version": string;
  readonly "protocolVersion": string;
  readonly "gatewayEpoch": string;
  readonly "processId": number;
};

export type MediaMetrics = {
  readonly "videoSessions": number;
  readonly "videoSources": number;
  readonly "audioSessions": number;
  readonly "audioSources": number;
  readonly "overlayMatched": number;
  readonly "overlayWaitTimeouts": number;
  readonly "overlayExpired": number;
  readonly "overlayRejected": number;
  readonly "audioDroppedChunks": number;
};

export type MediaSample = {
  readonly "source": string;
  readonly "format": string;
  readonly "frameId": number;
  readonly "tsMs": number;
  readonly "width": number;
  readonly "height": number;
  readonly "x": number;
  readonly "y": number;
  readonly "finite": boolean;
  readonly "value": JsonValue;
  readonly "streamId"?: string;
  readonly "streamEpoch"?: string;
};

export type MediaSessionAnswer = {
  readonly "sessionId": string;
  readonly "source": string;
  readonly "quality": string;
  readonly "sdp": string;
  readonly "type": "answer";
  readonly "maxWidth": number;
  readonly "maxHeight": number;
  readonly "maxFps": number;
  readonly "overlay": boolean;
};

export type MediaSessionOffer = {
  readonly "source": string;
  readonly "quality": string;
  readonly "sdp": string;
  readonly "type"?: string;
  readonly "overlay"?: boolean;
};

export type ModelCapabilities = {
  readonly "modelId": string;
  readonly "imageInput"?: boolean | null;
  readonly "thinking"?: boolean | null;
  readonly "source"?: "catalog" | "legacy";
  readonly "imageSource"?: "catalog" | "legacy" | "manual" | null;
  readonly "thinkingSource"?: "catalog" | "legacy" | "manual" | null;
};

export type NodeLayout = {
  readonly "nodeId": string;
  readonly "x": number;
  readonly "y": number;
  readonly "width"?: number | null;
  readonly "height"?: number | null;
  readonly "collapsed"?: boolean;
};

export type NoulAnswer = {
  readonly "type": "noul";
  readonly "noul": number;
};

export type NoulQuestion = {
  readonly "type": "noul";
  readonly "instructions": string | Readonly<Record<string, JsonValue>> | ReadonlyArray<JsonValue>;
  readonly "criteria"?: Readonly<Record<string, string | Readonly<Record<string, JsonValue>> | ReadonlyArray<JsonValue>>>;
};

export type OperatorNode = {
  readonly "kind": "operator";
  readonly "nodeId": string;
  readonly "name": string;
  readonly "serviceId": string;
  readonly "serviceClass": string;
  readonly "operatorClass": string;
  readonly "spec": F8OperatorSpec;
  readonly "ports"?: ReadonlyArray<GraphPort>;
  readonly "portIds"?: Readonly<Record<string, string>>;
  readonly "stateValues"?: Readonly<Record<string, JsonValue>>;
  readonly "enabled"?: boolean;
};

export type OverlayDetection = {
  readonly "x": number;
  readonly "y": number;
  readonly "width": number;
  readonly "height": number;
  readonly "label"?: string;
  readonly "score"?: number | null;
};

export type OverlayResult = {
  readonly "source": string;
  readonly "streamId": string;
  readonly "streamEpoch": string;
  readonly "frameId": number;
  readonly "captureTimestampMs": number;
  readonly "detections": ReadonlyArray<OverlayDetection>;
};

export type PatchRequest = {
  readonly "requestId": string;
  readonly "expectedGraphRevision": number;
  readonly "expectedLayoutRevision": number;
  readonly "operations": ReadonlyArray<CreateNodeOp | DeleteNodeOp | ConnectEdgeOp | DisconnectEdgeOp | SetNodeStateOp | RenameNodeOp | SetServiceSpecOp | SetOperatorSpecOp | RefreshInstalledSpecOp | BindOperatorServiceOp | SetNodeEnabledOp | SetNodeLayoutOp | InsertFragmentOp>;
};

export type PatchResult = {
  readonly "requestId": string;
  readonly "document": StudioDocument;
  readonly "graphChanged": boolean;
  readonly "layoutChanged": boolean;
  readonly "runtimeErrors"?: ReadonlyArray<string>;
};

export type PortDirection = "input" | "output";

export type PortKind = "command" | "data" | "exec" | "state";

export type PresentationCommand = {
  readonly "nodeId": string;
  readonly "command": string;
  readonly "payload": Readonly<Record<string, JsonValue>>;
  readonly "tsMs"?: number | null;
};

export type PreviewUnityInstallRequest = {
  readonly "targetPath": string;
  readonly "exporter"?: "auto" | "live2d" | "skeleton";
  readonly "udpPort"?: number;
  readonly "offline"?: boolean;
  readonly "forceReinstall"?: boolean;
  readonly "skipExporter"?: boolean;
};

export type ProbeProviderRequest = {
  readonly "protocol": "anthropic" | "openai_chat" | "openai_responses" | "systemone";
  readonly "endpoint": string;
  readonly "apiKey"?: string;
  readonly "providerId"?: string;
  readonly "model"?: string;
  readonly "verifyModel"?: boolean;
};

export type ProjectRecord = {
  readonly "projectId": string;
  readonly "name": string;
  readonly "description": string;
  readonly "createdAt": string;
  readonly "updatedAt": string;
  readonly "document": StudioDocument;
};

export type ProjectSummary = {
  readonly "projectId": string;
  readonly "name": string;
  readonly "description": string;
  readonly "createdAt": string;
  readonly "updatedAt": string;
  readonly "graphRevision": number;
  readonly "layoutRevision": number;
};

export type ProjectVersion = {
  readonly "versionId": string;
  readonly "projectId": string;
  readonly "name": string;
  readonly "createdAt": string;
  readonly "document": StudioDocument;
};

export type ProviderProbeResult = {
  readonly "connected": boolean;
  readonly "models": ReadonlyArray<string>;
  readonly "detail": string;
  readonly "verified": "catalog" | "model" | "none";
  readonly "modelCapabilities"?: ReadonlyArray<ModelCapabilities>;
};

export type ProviderSettingsView = {
  readonly "providerId": string;
  readonly "displayName": string;
  readonly "model": string;
  readonly "endpoint": string;
  readonly "apiKeySet": boolean;
  readonly "requiresApiKey": boolean;
  readonly "configured": boolean;
  readonly "source": string;
  readonly "kind"?: "agent" | "decision";
  readonly "inputModalities"?: ReadonlyArray<"image" | "text">;
  readonly "supportsImage"?: boolean;
  readonly "protocol"?: "anthropic" | "openai_chat" | "openai_responses" | "systemone" | null;
  readonly "models"?: ReadonlyArray<string>;
  readonly "custom"?: boolean;
  readonly "modelCapabilities"?: ReadonlyArray<ModelCapabilities>;
};

export type RefreshInstalledSpecOp = {
  readonly "op": "refreshInstalledSpec";
  readonly "nodeId": string;
};

export type RegisterHotkeyRequest = {
  readonly "accelerator": string;
  readonly "projectId": string;
  readonly "nodeId": string;
  readonly "field": string;
  readonly "bindingId"?: string | null;
};

export type RenameAgentSessionRequest = {
  readonly "title": string;
};

export type RenameNodeOp = {
  readonly "op": "renameNode";
  readonly "nodeId": string;
  readonly "name": string;
};

export type ResolveAgentApprovalRequest = {
  readonly "approved": boolean;
  readonly "argumentsHash": string;
};

export type RuntimeActionResult = {
  readonly "success": boolean;
  readonly "result": JsonValue;
  readonly "errorMessage": string;
};

export type RuntimeNodeState = {
  readonly "serviceId": string;
  readonly "nodeId": string;
  readonly "fields": ReadonlyArray<RuntimeStateField>;
};

export type RuntimeStateField = {
  readonly "field": string;
  readonly "found": boolean;
  readonly "value": JsonValue;
  readonly "tsMs": number | null;
};

export type RuntimeStateReadRequest = {
  readonly "fields": ReadonlyArray<string>;
};

export type SchemaMode = "basic_recursive";

export type SchemaVersion1 = "f8monitor/1";

export type ScoreAnswer = {
  readonly "type": "score";
  readonly "score": number;
  readonly "legend": Readonly<Record<string, string | Readonly<Record<string, JsonValue>> | ReadonlyArray<JsonValue>>>;
  readonly "probabilities": Readonly<Record<string, number>>;
  readonly "confidence": number;
};

export type ScoreQuestion = {
  readonly "type": "score";
  readonly "instructions": string | Readonly<Record<string, JsonValue>> | ReadonlyArray<JsonValue>;
  readonly "criteria": ReadonlyArray<string | Readonly<Record<string, JsonValue>> | ReadonlyArray<JsonValue>>;
};

export type SelectAgentModelRequest = {
  readonly "providerId": string;
  readonly "modelId": string;
};

export type SerialPortInfo = {
  readonly "device": string;
  readonly "description": string;
  readonly "hardwareId": string;
};

export type ServerCapabilities = {
  readonly "graph_editing": boolean;
  readonly "runtime_control": boolean;
  readonly "web_assets": boolean;
  readonly "web_rtc_video": boolean;
  readonly "web_rtc_audio": boolean;
  readonly "three_d": boolean;
  readonly "agent_tools": boolean;
};

export type ServiceActiveRequest = {
  readonly "active": boolean;
};

export type ServiceCommandRequest = {
  readonly "call": string;
  readonly "params"?: Readonly<Record<string, JsonValue>>;
};

export type ServiceDeployResult = {
  readonly "serviceId": string;
  readonly "success": boolean;
  readonly "errorMessage": string;
};

export type ServiceNode = {
  readonly "kind": "service";
  readonly "nodeId": string;
  readonly "name": string;
  readonly "serviceId": string;
  readonly "serviceClass": string;
  readonly "spec": F8ServiceSpec;
  readonly "ports"?: ReadonlyArray<GraphPort>;
  readonly "portIds"?: Readonly<Record<string, string>>;
  readonly "stateValues"?: Readonly<Record<string, JsonValue>>;
  readonly "enabled"?: boolean;
};

export type ServiceRuntimeStatus = {
  readonly "serviceId": string;
  readonly "serviceClass": string;
  readonly "runtimeInstanceId": string;
  readonly "active": boolean;
  readonly "rungraphGraphId"?: string;
  readonly "rungraphRevision"?: string;
  readonly "rungraphFingerprint"?: string;
};

export type ServiceStartRequest = {
  readonly "serviceClass": string;
};

export type ServiceStateRequest = {
  readonly "nodeId": string;
  readonly "field": string;
  readonly "value": JsonValue;
};

export type SetNodeEnabledOp = {
  readonly "op": "setNodeEnabled";
  readonly "nodeId": string;
  readonly "enabled": boolean;
};

export type SetNodeLayoutOp = {
  readonly "op": "setNodeLayout";
  readonly "layout": NodeLayout;
};

export type SetNodeStateOp = {
  readonly "op": "setNodeState";
  readonly "nodeId": string;
  readonly "field": string;
  readonly "value": JsonValue;
};

export type SetOperatorSpecOp = {
  readonly "op": "setOperatorSpec";
  readonly "nodeId": string;
  readonly "spec": F8OperatorSpec;
  readonly "portRenames"?: Readonly<Record<string, string>>;
};

export type SetServiceSpecOp = {
  readonly "op": "setServiceSpec";
  readonly "nodeId": string;
  readonly "spec": F8ServiceSpec;
  readonly "portRenames"?: Readonly<Record<string, string>>;
};

export type SkeletonUdpVerification = {
  readonly "bindAddress": string;
  readonly "port": number;
  readonly "packetCount": number;
  readonly "decodedFrameCount": number;
  readonly "modelNames": ReadonlyArray<string>;
  readonly "decoderErrors": ReadonlyArray<string>;
  readonly "verified": boolean;
};

export type Source = "data_in_ports";

export type Source1 = "state_fields";

export type Source2 = "data_out_ports";

export type StartAgentRunRequest = {
  readonly "prompt": string;
  readonly "images"?: ReadonlyArray<AgentImage>;
  readonly "reasoningEffort"?: "high" | "low" | "medium" | null;
};

export type StudioDocument = {
  readonly "schemaVersion": string;
  readonly "projectId": string;
  readonly "graphId": string;
  readonly "graphRevision": number;
  readonly "layoutRevision": number;
  readonly "nodes"?: ReadonlyArray<ServiceNode | OperatorNode>;
  readonly "edges"?: ReadonlyArray<GraphEdge>;
  readonly "layout"?: ReadonlyArray<NodeLayout>;
};

export type ToolCallStatus = "cancelled" | "denied" | "failed" | "queued" | "running" | "succeeded" | "waiting_for_approval";

export type UnityInstallPlan = {
  readonly "planId": string;
  readonly "targetPath": string;
  readonly "actions": ReadonlyArray<string>;
  readonly "blockingErrors": ReadonlyArray<string>;
  readonly "filesToWrite": ReadonlyArray<string>;
  readonly "filesToPreserve": ReadonlyArray<string>;
  readonly "graphBuildPlan": JsonValue;
  readonly "raw": JsonValue;
};

export type UpdateAssetRequest = {
  readonly "name": string;
  readonly "content": JsonValue;
  readonly "description"?: string;
  readonly "tags"?: ReadonlyArray<string>;
};

export type UpdateEditorDocumentRequest = {
  readonly "version": number;
  readonly "text": string;
};

export type UpdateProjectRequest = {
  readonly "name": string;
  readonly "description"?: string;
};

export type UpdateProviderSettings = {
  readonly "model": string;
  readonly "endpoint"?: string;
  readonly "apiKey"?: string | null;
  readonly "clearApiKey"?: boolean;
  readonly "supportsImage"?: boolean | null;
  readonly "displayName"?: string;
  readonly "models"?: ReadonlyArray<string>;
  readonly "modelCapabilities"?: ReadonlyArray<ModelCapabilities>;
};

export type ValidateDocumentRequest = {
  readonly "document": StudioDocument;
};

export type ValidationResponse = {
  readonly "valid": boolean;
  readonly "graphRevision": number;
  readonly "layoutRevision": number;
};

export type VerifySkeletonUdpRequest = {
  readonly "bindAddress"?: string;
  readonly "port"?: number;
  readonly "timeoutMs"?: number;
  readonly "minimumFrames"?: number;
};

