schemaVersion: f8serviceEntry/1
serviceClass: f8.cppengine
label: CppEngine
version: 0.0.1
launch:
  command: ./f8cppengine_service
  args: []
  env: {}
  workdir: ../../../runtime/bundles/f8.cppengine/0.0.1/linux
