schemaVersion: f8serviceEntry/1
serviceClass: f8.implayer
label: IM Player
version: 0.0.1
launch:
  command: ./f8implayer_service
  args: []
  env: {}
  workdir: ../../../runtime/bundles/f8.implayer/0.0.1/linux
