"""Generate key builders; callers retain token validation and path normalization."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from string import Formatter

ROOT = Path(__file__).resolve().parents[1]


def generate() -> dict[Path, str]:
    templates: dict[str, str] = json.loads((ROOT / "schemas/runtime-keys.json").read_text())
    py = [
        "# Generated by scripts/generate_runtime_keys.py; do not edit.",
        "# Arguments must already be validated/normalized by the public naming API.",
        "",
    ]
    cpp = [
        "// Generated by scripts/generate_runtime_keys.py; do not edit.",
        "#pragma once",
        "#include <string>",
        "",
        "namespace f8::cppsdk::wire_keys {",
        "",
    ]
    for name, template in templates.items():
        parts = list(Formatter().parse(template))
        fields = [field for _, field, _, _ in parts if field is not None]
        if any(not field.isidentifier() for field in fields) or not name.isidentifier():
            raise ValueError(f"Invalid key definition: {name}")
        py += [
            "",
            f"def {name}({', '.join(field + ': str' for field in fields)}) -> str:",
            f"    return f{template!r}",
            "",
        ]
        terms = [
            term
            for literal, field, _, _ in parts
            for term in ([json.dumps(literal)] if field is None else [json.dumps(literal), field])
            if term != '""'
        ]
        cpp += [
            f"inline std::string {name}({', '.join('const std::string& ' + field for field in fields)}) {{",
            "  return std::string(" + terms[0] + ") + " + " + ".join(terms[1:]) + ";",
            "}",
            "",
        ]
    cpp += ["}  // namespace f8::cppsdk::wire_keys", ""]
    return {
        ROOT / "packages/f8pysdk/f8pysdk/generated/runtime_keys.py": "\n".join(py),
        ROOT / "packages/f8cppsdk/include/f8cppsdk/generated/runtime_keys.h": "\n".join(cpp),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale generated key contract: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
