from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True)
class OperatorRow:
    operator_class: str
    label: str
    description: str


@dataclass(frozen=True)
class ServiceRow:
    service_class: str
    label: str
    description: str
    operators: list[OperatorRow]


def _as_dict(value: Any, *, ctx: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{ctx}: expected object, got {type(value).__name__}")
    return value


def _slugify(value: str) -> str:
    return value.strip().replace(".", "-").replace("_", "-").replace(" ", "-")


def _first_sentence(text: str) -> str:
    cleaned = str(text or "").strip().replace("\n", " ")
    if not cleaned:
        return "No description."
    if "." in cleaned:
        return cleaned.split(".", 1)[0].strip() + "."
    return cleaned


def _platform_service_yml_names() -> list[str]:
    if os.name == "nt":
        return ["service.win.yml"]
    return ["service.linux.yml"]


def _find_service_dirs(services_root: Path) -> list[Path]:
    names = _platform_service_yml_names() + ["service.yml", "service.mac.yml", "service.win.yml", "service.linux.yml"]
    found: set[Path] = set()
    for name in names:
        for path in services_root.rglob(name):
            found.add(path.parent)
    return sorted(found)


def _load_service_row(service_dir: Path, *, describe_path: Path | None = None) -> ServiceRow:
    describe_path = describe_path or service_dir / "describe.json"
    if not describe_path.exists():
        raise ValueError(f"missing describe.json: {service_dir}")
    raw = json.loads(describe_path.read_text(encoding="utf-8"))
    root = _as_dict(raw, ctx=str(describe_path))
    service_obj = _as_dict(root.get("service"), ctx=f"{describe_path}.service")
    operators_raw = root.get("operators")
    if operators_raw is None:
        operators_list: list[Any] = []
    elif isinstance(operators_raw, list):
        operators_list = operators_raw
    else:
        raise ValueError(f"{describe_path}: service.operators must be a list")

    operators: list[OperatorRow] = []
    for index, operator_raw in enumerate(operators_list):
        operator_obj = _as_dict(operator_raw, ctx=f"{describe_path}.service.operators[{index}]")
        operators.append(
            OperatorRow(
                operator_class=str(operator_obj.get("operatorClass") or "").strip(),
                label=str(operator_obj.get("label") or operator_obj.get("operatorClass") or "").strip(),
                description=str(operator_obj.get("description") or "").strip(),
            )
        )

    return ServiceRow(
        service_class=str(service_obj.get("serviceClass") or "").strip(),
        label=str(service_obj.get("label") or "").strip(),
        description=str(service_obj.get("description") or "").strip(),
        operators=operators,
    )


def _family_name(service_class: str) -> str:
    if service_class.startswith("f8.cvkit."):
        return "CVKit"
    if service_class.startswith("f8.dl."):
        return "Deep Learning"
    if service_class.startswith("f8.mp."):
        return "MediaPipe"
    return "Core"


def _render_service_nodes(rows: list[ServiceRow]) -> str:
    groups: dict[str, list[ServiceRow]] = {"Core": [], "CVKit": [], "Deep Learning": [], "MediaPipe": []}
    for row in rows:
        groups[_family_name(row.service_class)].append(row)

    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/generate_node_atlas.py. DO NOT EDIT DIRECTLY. -->",
        "# Service Nodes",
        "",
        "Canonical service documentation lives under `Modules > Services`; this page is the release inventory view.",
        "",
    ]

    for family in ("Core", "CVKit", "Deep Learning", "MediaPipe"):
        family_rows = sorted(groups[family], key=lambda item: item.service_class)
        if not family_rows:
            continue
        lines.append(f"## {family}")
        lines.append("")
        lines.append("| Service Node | Label | Main Role | Operators | Canonical Doc |")
        lines.append("| --- | --- | --- | --- | --- |")
        for row in family_rows:
            slug = _slugify(row.service_class)
            lines.append(
                "| "
                f"`{row.service_class}` | "
                f"{row.label} | "
                f"{_first_sentence(row.description).replace('|', '\\|')} | "
                f"`{len(row.operators)}` | "
                f"[Open](../modules/services/{slug}.md) |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_pyengine_operators(rows: list[ServiceRow]) -> str:
    pyengine = next((row for row in rows if row.service_class == "f8.pyengine"), None)
    if pyengine is None:
        raise ValueError("f8.pyengine not found in service inventory")

    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/generate_node_atlas.py. DO NOT EDIT DIRECTLY. -->",
        "# PyEngine Operators",
        "",
        "`f8.pyengine` is the main operator host in this repo. Each operator below links back to its canonical spec + usage section.",
        "",
        "| Operator | Label | Main Role | Canonical Doc |",
        "| --- | --- | --- | --- |",
    ]
    for operator in pyengine.operators:
        anchor = _slugify(operator.operator_class)
        lines.append(
            "| "
            f"`{operator.operator_class}` | "
            f"{operator.label} | "
            f"{_first_sentence(operator.description).replace('|', '\\|')} | "
            f"[Open](../modules/services/f8-pyengine.md#operator-{anchor}) |"
        )
    lines.append("")
    return "\n".join(lines)


def _build_expected(services_root: Path, *, service_nodes_path: Path, pyengine_operators_path: Path) -> dict[Path, str]:
    if services_root.suffix == ".json":
        from f8pysdk.service_runtime_tools.inventory.index import service_index_sources
        rows = [_load_service_row(manifest.parent, describe_path=describe)
                for manifest, describe in service_index_sources(services_root)]
    else:
        rows = [_load_service_row(service_dir) for service_dir in _find_service_dirs(services_root)]
    rows = sorted(rows, key=lambda item: item.service_class)
    return {
        service_nodes_path: _render_service_nodes(rows),
        pyengine_operators_path: _render_pyengine_operators(rows),
    }


def _check(expected: dict[Path, str]) -> int:
    mismatches: list[str] = []
    for path, content in expected.items():
        if not path.exists():
            mismatches.append(f"MISSING: {path}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != content:
            mismatches.append(f"DIFFERS: {path}")
    if mismatches:
        print("node atlas docs are out of date:")
        for mismatch in mismatches:
            print(f"- {mismatch}")
        return 1
    print("node atlas docs are up to date")
    return 0


def _write(expected: dict[Path, str]) -> None:
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def build(
    *, services_root: Path, service_nodes_path: Path, pyengine_operators_path: Path, check: bool
) -> int:
    expected = _build_expected(
        services_root,
        service_nodes_path=service_nodes_path,
        pyengine_operators_path=pyengine_operators_path,
    )
    if check:
        return _check(expected)

    _write(expected)
    print("generated 2 node atlas page(s)")
    return 0


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate node-atlas inventory pages")
    parser.add_argument("--service-index", "--services-root", dest="services_root", default="config/service-index.json", help="Service index (or explicit legacy fixture directory)")
    parser.add_argument("--service-nodes-path", default="docs/node-atlas/service-nodes.md")
    parser.add_argument("--pyengine-operators-path", default="docs/node-atlas/pyengine-operators.md")
    parser.add_argument("--check", action="store_true", help="Validate generated files without writing")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    service_nodes_path = Path(args.service_nodes_path).resolve()

    return build(
        services_root=Path(args.services_root).resolve(),
        service_nodes_path=service_nodes_path,
        pyengine_operators_path=Path(args.pyengine_operators_path).resolve(),
        check=bool(args.check),
    )


if __name__ == "__main__":
    raise SystemExit(main())
