"""Generate explicit binary header codecs from the shared little-endian schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KINDS = {"u32": ("I", "std::uint32_t", 4), "u64": ("Q", "std::uint64_t", 8), "i64": ("q", "std::int64_t", 8)}


def generate() -> dict[Path, str]:
    schema = json.loads((ROOT / "schemas/stream-wire.json").read_text())
    if schema["byte_order"] != "little":
        raise ValueError("Only little-endian stream schemas are supported")
    py = [
        "# Generated by scripts/generate_stream_wire.py; do not edit.",
        "from __future__ import annotations",
        "",
        "import struct",
        "from typing import NamedTuple",
        "",
    ]
    cpp = [
        "// Generated by scripts/generate_stream_wire.py; do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <cstring>",
        "",
        "namespace f8::cppsdk {",
        "",
    ]
    for python_name, cpp_name, value in schema["constants"]:
        py.append(f"{python_name} = {value}")
        cpp.append(f"inline constexpr std::uint32_t {cpp_name} = {value}u;")
    for header in schema["headers"]:
        name, fields, prefix, cp = header["name"], header["fields"], header["prefix"], header["cpp_prefix"]
        fmt = "<" + "".join(KINDS[kind][0] for _, kind in fields)
        size = sum(KINDS[kind][2] for _, kind in fields)
        py += [
            "",
            f"{prefix}_MAGIC = {header['magic']}",
            f"{prefix}_SCHEMA_VERSION = {header['version']}",
            f"{prefix}_HEADER_BYTES = {size}",
            f"_{name}_STRUCT = struct.Struct({fmt!r})",
            "",
            "",
            f"class {name}(NamedTuple):",
        ]
        py += [f"    {field}: int" for field, _ in fields]
        py += [
            "",
            "    def pack(self) -> bytes:",
            f"        return _{name}_STRUCT.pack(",
            *[f"            self.{field}," for field, _ in fields],
            "        )",
            "",
            "    @classmethod",
            f"    def unpack_from(cls, data: bytes | bytearray | memoryview) -> {name}:",
            f"        values = _{name}_STRUCT.unpack_from(data)",
            "        return cls(",
            *[f"            {field}=int(values[{i}])," for i, (field, _) in enumerate(fields)],
            "        )",
            "",
        ]
        cpp += [
            "",
            f"inline constexpr std::uint32_t {cp}Magic = {header['magic']}u;",
            f"inline constexpr std::uint32_t {cp}SchemaVersion = {header['version']}u;",
            f"inline constexpr std::uint32_t {cp}HeaderBytes = {size}u;",
            "",
            f"struct {name} {{",
        ]
        cpp += [f"  {KINDS[kind][1]} {field} = 0;" for field, kind in fields]
        cpp += [
            "",
            "  // The caller supplies a buffer of at least HeaderBytes bytes.",
            "  void encode(std::uint8_t* out) const {",
        ]
        offset = 0
        for field, kind in fields:
            width = KINDS[kind][2]
            cpp += [
                f"    for (unsigned i = 0; i < {width}; ++i) {{",
                f"      out[{offset} + i] = static_cast<std::uint8_t>(static_cast<std::uint64_t>({field}) >> (i * 8));",
                "    }",
            ]
            offset += width
        cpp += [
            "  }",
            "",
            f"  static bool decode(const std::uint8_t* data, std::size_t size, {name}& out) {{",
            f"    if (data == nullptr || size < {cp}HeaderBytes) return false;",
        ]
        offset = 0
        for field, kind in fields:
            width = KINDS[kind][2]
            cpp += [
                f"    std::uint64_t bits_{field} = 0;",
                f"    for (unsigned i = 0; i < {width}; ++i) {{",
                f"      bits_{field} |= static_cast<std::uint64_t>(data[{offset} + i]) << (i * 8);",
                "    }",
            ]
            if kind == "i64":
                cpp.append(f"    std::memcpy(&out.{field}, &bits_{field}, sizeof(out.{field}));")
            else:
                cpp.append(f"    out.{field} = static_cast<{KINDS[kind][1]}>(bits_{field});")
            offset += width
        cpp += ["    return true;", "  }", "};"]
    cpp += ["", "}  // namespace f8::cppsdk", ""]
    return {
        ROOT / "packages/f8pysdk/f8pysdk/generated/stream_wire.py": "\n".join(py),
        ROOT / "packages/f8cppsdk/include/f8cppsdk/generated/stream_wire.h": "\n".join(cpp),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale generated stream contract: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
