"""Generate shared control names and deployment fingerprint normalization policy."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate() -> dict[Path, str]:
    control = json.loads((ROOT / "schemas/runtime-control.json").read_text())
    policy = json.loads((ROOT / "schemas/rungraph-fingerprint.json").read_text())
    names = control["shared"] + control["python_only"]
    py_control = "# Generated by scripts/generate_runtime_policy.py; do not edit.\nfrom enum import StrEnum\n\n\nclass ControlEndpoint(StrEnum):\n"
    py_control += "".join(f"    {name} = {name!r}\n" for name in names)
    py_control += (
        "\nSHARED_CONTROL_ENDPOINTS = (" + ", ".join("ControlEndpoint." + name for name in control["shared"]) + ",)\n"
    )
    py_control += (
        "PYTHON_ONLY_CONTROL_ENDPOINTS = ("
        + ", ".join("ControlEndpoint." + name for name in control["python_only"])
        + ",)\n"
    )
    cpp_control = (
        "// Generated by scripts/generate_runtime_policy.py; do not edit.\n#pragma once\n#include <array>\n#include <string_view>\nnamespace f8::cppsdk {\nenum class ControlEndpoint { "
        + ", ".join(names)
        + " };\n"
    )
    cpp_control += "inline constexpr std::string_view endpoint_name(ControlEndpoint value) {\n  switch (value) {\n"
    cpp_control += "".join(f'    case ControlEndpoint::{name}: return "{name}";\n' for name in names)
    cpp_control += "  }\n  return {};\n}\n"
    cpp_control += (
        f"inline constexpr std::array<ControlEndpoint,{len(control['shared'])}> kSharedControlEndpoints{{"
        + ", ".join("ControlEndpoint::" + name for name in control["shared"])
        + "};\n}\n"
    )
    py = """# Generated by scripts/generate_runtime_policy.py; do not edit.
from __future__ import annotations

import json
from typing import Any

"""
    py += "POLICY: dict[str, Any] = " + repr(policy) + "\n\n"
    py += """def _sort_key(value: Any, fields: list[str]) -> tuple[str, ...]:
    if not isinstance(value, dict):
        return tuple("" for _ in fields)
    return tuple(str(value.get(field) or "") for field in fields)


def normalize_snapshot(graph: Any) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for collection, rules in POLICY["collections"].items():
        raw = graph.get(collection) if isinstance(graph, dict) else None
        items: list[dict[str, Any]] = []
        for source in raw if isinstance(raw, list) else []:
            item = {key: value for key, value in source.items() if key not in rules["omit"]} if isinstance(source, dict) else {}
            if collection == "nodes":
                for field in POLICY["node_sorted_strings"]:
                    value = item.get(field)
                    if isinstance(value, list):
                        item[field] = sorted(str(element) for element in value)
                for field, spec_rules in POLICY["node_named_specs"].items():
                    value = item.get(field)
                    if isinstance(value, list):
                        normalized = []
                        for spec in value:
                            if isinstance(spec, dict):
                                spec = {key: element for key, element in spec.items()
                                        if key not in spec_rules["omit"] and not
                                        (key in spec_rules["omit_defaults"] and element == spec_rules["omit_defaults"][key])}
                            normalized.append(spec)
                        item[field] = sorted(normalized, key=lambda spec: _sort_key(spec, POLICY["spec_sort"]))
            items.append(item)
        result[collection] = sorted(items, key=lambda item: _sort_key(item, rules["sort"]))
    return result


def fingerprint(graph: Any) -> str:
    return json.dumps(normalize_snapshot(graph), sort_keys=True, separators=(",", ":"))
"""
    cpp = """// Generated by scripts/generate_runtime_policy.py; do not edit.
#pragma once
#include <algorithm>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
namespace f8::cppsdk::wire_policy {
using json = nlohmann::json;
"""
    cpp += (
        'inline const json& policy() { static const json value = json::parse(R"F8POLICY('
        + json.dumps(policy, separators=(",", ":"))
        + ')F8POLICY"); return value; }\n'
    )
    cpp += """inline std::vector<std::string> sort_key(const json& value, const json& fields) {
  std::vector<std::string> key;
  for (const auto& field : fields) {
    const auto name=field.get<std::string>();
    if (!value.is_object() || !value.contains(name) || value[name].is_null()) key.emplace_back();
    else key.push_back(value[name].is_string() ? value[name].get<std::string>() : value[name].dump());
  }
  return key;
}
inline json normalize_snapshot(const json& graph) {
  json result=json::object();
  for (const auto& collection : policy()["collections"].items()) {
    const auto& name=collection.key(); const auto& rules=collection.value();
    auto items=json::array();
    if (graph.is_object() && graph.contains(name) && graph[name].is_array()) {
      for (const auto& source : graph[name]) {
        auto item=source.is_object() ? source : json::object();
        for (const auto& field : rules["omit"]) item.erase(field.get<std::string>());
        if (name=="nodes") {
          for (const auto& field : policy()["node_sorted_strings"]) {
            const auto key=field.get<std::string>();
            if (item.contains(key) && item[key].is_array()) std::sort(item[key].begin(),item[key].end());
          }
          for (const auto& field : policy()["node_named_specs"].items()) {
            if (!item.contains(field.key()) || !item[field.key()].is_array()) continue;
            auto& specs=item[field.key()];
            for (auto& spec : specs) {
              if (!spec.is_object()) continue;
              for (const auto& omitted : field.value()["omit"]) spec.erase(omitted.get<std::string>());
              for (const auto& def : field.value()["omit_defaults"].items()) {
                if (spec.contains(def.key()) && spec[def.key()]==def.value()) spec.erase(def.key());
              }
            }
            std::stable_sort(specs.begin(),specs.end(),[](const json& a,const json& b) { return sort_key(a,policy()["spec_sort"]) < sort_key(b,policy()["spec_sort"]); });
          }
        }
        items.push_back(std::move(item));
      }
    }
    std::stable_sort(items.begin(),items.end(),[&rules](const json& a,const json& b) { return sort_key(a,rules["sort"]) < sort_key(b,rules["sort"]); });
    result[name]=std::move(items);
  }
  return result;
}
inline std::string fingerprint(const json& graph) { return normalize_snapshot(graph).dump(-1,' ',true,json::error_handler_t::strict); }
}
"""
    return {
        ROOT / "packages/f8pysdk/f8pysdk/generated/control.py": py_control,
        ROOT / "packages/f8cppsdk/include/f8cppsdk/generated/control.h": cpp_control,
        ROOT / "packages/f8pysdk/f8pysdk/generated/runtime_fingerprint.py": py,
        ROOT / "packages/f8cppsdk/include/f8cppsdk/generated/runtime_fingerprint.h": cpp,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Stale generated runtime policy: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
