openapi: 3.0.3
info:
  title: ServiceHostBase API (NATS binding)
  version: "v1"
  description: >
    Common control plane verbs exposed by every service instance (including engine). Subjects use the instanceId to avoid load-balancing.
servers:
  - url: nats://local
    description: NATS request/reply (canonical transport)
paths:
  /{instanceId}/activate:
    post:
      summary: Activate service
      operationId: activateService
      x-nats-subject: f8.{instanceId}.activate
      parameters:
        - $ref: '#/components/parameters/instanceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Envelope'
      responses:
        "200":
          description: Ack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckReply'
  /{instanceId}/deactivate:
    post:
      summary: Deactivate service
      operationId: deactivateService
      x-nats-subject: f8.{instanceId}.deactivate
      parameters:
        - $ref: '#/components/parameters/instanceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Envelope'
      responses:
        "200":
          description: Ack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckReply'
  /{instanceId}/terminate:
    post:
      summary: Terminate service
      operationId: terminateService
      x-nats-subject: f8.{instanceId}.terminate
      parameters:
        - $ref: '#/components/parameters/instanceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Envelope'
      responses:
        "200":
          description: Ack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckReply'
  /{instanceId}/deployOpGraph:
    post:
      summary: Deploy per-instance subgraph
      description: Master sends compiled subgraph/half-edges to the service; applied at safe point.
      operationId: deployOpGraph
      x-nats-subject: f8.{instanceId}.deployOpGraph
      x-nats-timeout-ms: 3000
      parameters:
        - $ref: '#/components/parameters/instanceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeployOpGraphRequest'
      responses:
        "200":
          description: Deploy result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeployOpGraphReply'
  /{instanceId}/status:
    get:
      summary: Current status
      operationId: getStatus
      x-nats-subject: f8.{instanceId}.status
      parameters:
        - $ref: '#/components/parameters/instanceId'
      responses:
        "200":
          description: Status snapshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusReply'
  /{instanceId}/state/snapshot:
    get:
      summary: State snapshot
      operationId: getStateSnapshot
      x-nats-subject: f8.{instanceId}.stateSnapshot
      parameters:
        - $ref: '#/components/parameters/instanceId'
      responses:
        "200":
          description: State snapshot reply
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateSnapshotReply'
  /{instanceId}/state/set:
    post:
      summary: Set state entry
      operationId: setState
      x-nats-subject: f8.{instanceId}.setState
      x-nats-timeout-ms: 1000
      parameters:
        - $ref: '#/components/parameters/instanceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StateSetRequest'
      responses:
        "200":
          description: State set result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckReply'
  /{instanceId}/cmd:
    post:
      summary: Service-defined command channel
      description: Invoke a manifest-defined command by name.
      operationId: serviceCommand
      x-nats-subject: f8.{instanceId}.cmd
      x-nats-timeout-ms: 2000
      parameters:
        - $ref: '#/components/parameters/instanceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceCommandRequest'
      responses:
        "200":
          description: Command reply
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceCommandReply'
components:
  parameters:
    instanceId:
      name: instanceId
      in: path
      required: true
      schema:
        type: string
  schemas:
    Envelope:
      type: object
      properties:
        msgId:
          type: string
          format: uuid
        traceId:
          type: string
          format: uuid
        clientId:
          type: string
        hop:
          type: integer
          minimum: 0
        ts:
          type: string
          format: date-time
        apiVersion:
          type: string
          example: v1
        payload:
          type: object
        headers:
          type: object
          additionalProperties:
            type: string
      required: [msgId, traceId, clientId, hop, ts, apiVersion, payload]
    AckReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status]
    DeployOpGraphRequest:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                graph:
                  type: object
                  description: Per-instance subgraph payload (opaque blob).
                revision:
                  type: integer
                  description: Optional expected revision/etag for concurrency control.
              required: [graph]
    DeployOpGraphReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                revision:
                  type: integer
                  description: KV revision after apply.
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status]
    StatusReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                summary:
                  type: object
                  description: Contents of `status/summary` (should include lifecycle status, starting|deactivated|activated|terminating|error).
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status, summary]
    StateSnapshotReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                state:
                  type: object
                  description: Current state snapshot.
                revision:
                  type: integer
                  description: KV revision/etag of the snapshot.
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status]
    StateSetRequest:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                key:
                  type: string
                  description: State key to set (e.g., state/foo).
                value:
                  description: Value to set.
                expectedRevision:
                  type: integer
                  description: Optional expected KV revision for optimistic concurrency.
              required: [key, value]
    ServiceCommandRequest:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                command:
                  type: string
                  description: Command name (as declared in manifest).
                params:
                  type: object
                  description: Command parameters.
              required: [command]
    ServiceCommandReply:
      allOf:
        - $ref: '#/components/schemas/Envelope'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                result:
                  description: Command-specific result.
                errorCode:
                  type: string
                  enum: [invalid, conflict, unauthorized, not-found, unavailable, timeout, internal]
                errorMessage:
                  type: string
              required: [status]
