openapi: 3.0.3
info:
  title: f8 Master API (NATS binding)
  version: "v1"
  description: >
    Control plane between Web and Master over NATS request/reply. Subjects are defined via `x-nats-*`.
servers:
  - url: nats://local
    description: NATS request/reply (canonical transport)
  - url: http://localhost:8080
    description: HTTP gateway that forwards to NATS for local testing/debugging
paths:
  /ping:
    post:
      summary: Liveness and capability exchange (client lease)
      description: Web checks daemon reachability, retrieves capabilities, and refreshes the single-client lease.
      operationId: ping
      x-nats-subject: f8.master.ping
      x-nats-timeout-ms: 1000
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PingRequest"
      responses:
        "200":
          description: Pong with capability info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PingReply"
  /graph/deploy:
    post:
      summary: Deploy a ServiceGraph
      description: Web sends the full ServiceGraph; master validates, compiles, launches missing instances, and rolls out subgraphs.
      operationId: deployGraph
      x-nats-subject: f8.master.deployGraph
      x-nats-timeout-ms: 5000
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeployGraphRequest"
      responses:
        "200":
          description: Deploy result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeployGraphReply"
  /registry/register:
    post:
      summary: Register a service instance with master
      description: Submit full manifest for validation and admission; master returns confirmed instanceId and KV info.
      operationId: registerService
      x-nats-subject: f8.master.registry.register
      x-nats-timeout-ms: 2000
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: Registration result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterReply"
  /registry/unregister:
    post:
      summary: Unregister a service instance with master
      description: Release registration and cleanup resources before exit.
      operationId: unregisterService
      x-nats-subject: f8.master.registry.unregister
      x-nats-timeout-ms: 2000
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UnregisterRequest"
      responses:
        "200":
          description: Unregister result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnregisterReply"
components:
  schemas:
    Envelope:
      type: object
      properties:
        msgId:
          type: string
          format: uuid
        traceId:
          type: string
          format: uuid
        clientId:
          type: string
        hop:
          type: integer
          minimum: 0
        ts:
          type: string
          format: date-time
        apiVersion:
          type: string
          example: v1
        payload:
          type: object
        headers:
          type: object
          additionalProperties:
            type: string
      required: [msgId, traceId, clientId, hop, ts, apiVersion, payload]
    ErrorBody:
      type: object
      properties:
        status:
          type: string
          enum: [error]
        errorCode:
          type: string
          enum:
            [
              invalid,
              conflict,
              unauthorized,
              not-found,
              unavailable,
              timeout,
              internal,
            ]
        errorMessage:
          type: string
      required: [status, errorCode]
    PingRequest:
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          properties:
            payload:
              type: object
              properties:
                requestedProfile:
                  type: string
                  description: Mode hint (web-only or web-plus-daemon)
              required: [requestedProfile]
    PingReply:
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok]
                leaseTtlMs:
                  type: integer
                  description: Client lease TTL; refreshed on each ping.
              required: [status, leaseTtlMs]
    DeployGraphRequest:
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          properties:
            payload:
              type: object
              properties:
                graph:
                  type: object
                  description: ServiceGraph document authored from Web.
                configVersion:
                  type: string
                  description: Optional optimistic version/etag.
              required: [graph]
    DeployGraphReply:
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                revision:
                  type: integer
                  description: Master-side compiled graph revision/etag.
                errorCode:
                  type: string
                  enum:
                    [
                      invalid,
                      conflict,
                      unauthorized,
                      not-found,
                      unavailable,
                      timeout,
                      internal,
                    ]
                errorMessage:
                  type: string
              required: [status]
    RegisterRequest:
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          properties:
            payload:
              type: object
              properties:
                serviceClass:
                  type: string
                  description: Required service type.
                instanceId:
                  type: string
                  description: Required instance id.
              required: [serviceClass, instanceId]
    RegisterReply:
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                instanceId:
                  type: string
                kvBucket:
                  type: string
                  description: KV bucket name assigned/confirmed
                token:
                  type: string
                  description: Bearer token to use for subsequent calls (Authorization header or envelope headers.authorization)
                errorCode:
                  type: string
                  enum:
                    [
                      invalid,
                      conflict,
                      unauthorized,
                      not-found,
                      unavailable,
                      timeout,
                      internal,
                    ]
                errorMessage:
                  type: string
              required: [status]
    UnregisterRequest:
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          properties:
            payload:
              type: object
              properties:
                instanceId:
                  type: string
                  description: Runtime-assigned id from registration
                manifestHash:
                  type: string
                  description: Optional sha256 to confirm same manifest
              required: [instanceId]
    UnregisterReply:
      allOf:
        - $ref: "#/components/schemas/Envelope"
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  type: string
                  enum: [ok, error]
                errorCode:
                  type: string
                  enum:
                    [
                      invalid,
                      conflict,
                      unauthorized,
                      not-found,
                      unavailable,
                      timeout,
                      internal,
                    ]
                errorMessage:
                  type: string
              required: [status]
    ServiceManifest:
      $ref: "../schemas/protocol.yml#/components/schemas/F8ServiceSpec"
